### PR TITLE
OC-11062 Time being displayed in "Date Started" field in Visits section of Participant Detail Page

### PR DESCRIPTION
**Pull request by theywa**
https://jira.openclinica.com/browse/OC-11062

### CODE REVIEW

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
