### PR TITLE
Paul's feedback on Reskin (WIP)

### PR DESCRIPTION
**Pull request by rooney**
https://github.com/OpenClinica/requirements/issues/28#issuecomment-316997967

### CODE REVIEW

**Comment by kkrumlian** [comment]
Hey Ron,
So we do have this SBSUrl in the datainfo.properties. Can we use this instead of return smURL
`SBSUrl=http://cust5.dev-sbs.openclinica.info:8080/user-service/api/users/`

**Comment by kkrumlian** [comment]
👍

**Comment by rooney** [comment]
roger

**Comment by kkrumlian** [comment]
@rooney I merged this either way. Let's make the change as part of next pull request pls

**Comment by rooney** [comment]
sure, thanks

**Pull request merged**
