### PR TITLE
OC-10811 jobUI page sorting and column name relabeling

### PR DESCRIPTION
**Pull request by rooney**
https://jira.openclinica.com/browse/OC-10811

### CODE REVIEW

**Comment by svadla-oc** [comment]
retest this please

**Comment by svadla-oc** [comment]
retest this please

**Comment by svadla-oc** [comment]
@rooney can you fix the conflicts please?

**Comment by rooney** [comment]
@svadla-oc conflicts resolved (y)

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
