### PR TITLE
OC-8255:Manual CRF import creates duplicate event CRF if a different …

### PR DESCRIPTION
**Pull request by Taoli2018**
…CRF version already has been started for that event.

### CODE REVIEW

**Comment by svadla-oc** [comment]
create a PR for 3.17.x branch

**Comment by Taoli2018** [comment]
created PR in 3.17:https://github.com/OpenClinica/OpenClinica/pull/3472

**Comment by Taoli2018** [comment]
this old PR is in 3.16

**Comment by svadla-oc** [comment]
Closing this since this is included in #3472

**Pull request closed without merging**
