### PR TITLE
OC-8603 feedback, OC-8490, OC-8649, and OC-8648 Progress

### PR DESCRIPTION
**Pull request by adison93**

### CODE REVIEW

**Comment by adison93** [comment]
OC-8490: Only Tech-Admin and Business Admin can delete an Event CRF
before:
before user
after in demo video:
https://drive.google.com/file/d/11lqPW1_tLxRxBY59hPwlmg8oFnQk81Fg/view?usp=sharing

**Comment by adison93** [comment]
OC-8648: Data Entry Person and CRC unable to submit Event and Subject level Queries
before:
CRC:
crc before
DEP:
dep before

after in demo video: https://drive.google.com/file/d/1iMSug74TgWysGZniM-9ywaIhyNbR0era/view?usp=sharing

**Comment by adison93** [comment]
OC-8649: Data Specialists and Investigators are unable to view Subject or Event level Queries in the Query Table
fixed in video: https://drive.google.com/file/d/1S1-rYKFs6oxukr91AbCf01w11jdTLG1U/view?usp=sharing

**Comment by kkrumlian** [comment]
👍

**Pull request merged**
