### PR TITLE
OC-13174: Added liquibase to update old sdv_status to new sdv_status

### PR DESCRIPTION
**Pull request by suthirr-openclinica**

### CODE REVIEW

**Comment by svadla-oc** [comment]
👍

**Comment by svadla-oc** [comment]
@suthirr-openclinica can you fix the conflicts please?

**Comment by suthirr-openclinica** [comment]
Resolved the conflicts @svadla-oc

**Comment by svadla-oc** [comment]
👍

**Comment by svadla-oc** [comment]
@suthirr-openclinica please fix conflicts

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
