### PR TITLE
OC-8667-2: Download Import Template

### PR DESCRIPTION
**Pull request by adison93**
Demo in: https://drive.google.com/file/d/1WZQeS5x3SaCrPU-N3vN0zpbfXqSqmlpa/view?usp=sharing

### CODE REVIEW

**Comment by pbowen-oc** [comment]
@kkrumlian - I posted an updated Import Template to the Jira issue. Please use that one instead of the previous version.

**Comment by adison93** [comment]
new import template: https://drive.google.com/file/d/1adRBVhug46QndYJZNrwQ1ckG_247go4R/view?usp=sharing

**Comment by pbowen-oc** [comment]
@kkrumlian - Please merge this.

**Comment by kkrumlian** [comment]
👍

**Pull request merged**
