### PR TITLE
OC-8660 Progress

### PR DESCRIPTION
**Pull request by adison93**
OC-8660: View Within Record for Subject Query should expand Subject Record section
fix in demo video: https://drive.google.com/file/d/1lLsLSqQTUT7FBw9zYkHmm3aGsD3rsfUQ/view?usp=sharing

### CODE REVIEW

**Comment by adison93** [comment]
OC-8660 : (New description) The View Query Within Record icon is currently broken and not functioning as a link. It looks like a tag is malformed.
fixed in demo video: https://drive.google.com/file/d/1BHG6FU6qsyXIyK6alQzHYPmr4qjDSUEb/view?usp=sharing

**Comment by adison93** [comment]
OC-8660:(feedback) View Within Record for Subject Query should expand Subject Record section
demo: https://drive.google.com/open?id=1ebBfkUEi2ZCOyT4XCbP8Z6iMeAjqjgEC

**Comment by adison93** [comment]
OC-8490: (feedback) Only Tech-Admin and Business Admin can delete an Event CRF
demo in: https://drive.google.com/file/d/1NiJnlfbRl-JVbrRIFQXV9K2OuEGfOneC/view?usp=sharing

**Comment by kkrumlian** [comment]
👍

**Pull request merged**
