### PR TITLE
OC-12440 (Update SDV Item Details table header layout) -- Jigyasa's f…

### PR DESCRIPTION
**Pull request by rooney**
…eedback: fix Site Name display

https://jira.openclinica.com/browse/OC-12440?focusedCommentId=202333&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-202333

### CODE REVIEW

**Comment by svadla-oc** [comment]
👍

**Comment by pbowen-oc** [comment]
@svadla-oc @rooney  - Please don't merge this. There was an error in the mockup in the ticket. I added a comment regarding the change needed.

**Comment by svadla-oc** [comment]
Okay. @rooney please update the PR per the new comment.

**Comment by rooney** [comment]
Okay updated @svadla-oc @pbowen-oc

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
