### PR TITLE
OC-10734 Page description on the jobs page

### PR DESCRIPTION
**Pull request by theywa**
https://jira.openclinica.com/browse/OC-10734

### CODE REVIEW

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
