### PR TITLE
OC-8693, OC-8674, OC-8490, OC-8691 Progress

### PR DESCRIPTION
**Pull request by adison93**
OC-8693 demo in: https://drive.google.com/file/d/1R7-w-x1Oy1dSYa3U5-gGedP6Y0zmPMhe/view?usp=sharing

### CODE REVIEW

**Comment by adison93** [comment]
OC-8764 in Runtime: https://drive.google.com/file/d/1egt_gpznuUX5VnWugVx_lz1w6317hFI8/view?usp=sharing

**Comment by adison93** [comment]
OC-8674 in Runtime: https://drive.google.com/file/d/1egt_gpznuUX5VnWugVx_lz1w6317hFI8/view?usp=sharing

**Comment by adison93** [comment]
demo in: https://drive.google.com/file/d/1TfL6TQE8lrQUeDWQT9cxwuZ4LTTsbBVI/view?usp=sharing

**Comment by pbowen-oc** [comment]
@kkrumlian - Can you merge and deploy this? I'd like to make sure I can test it Monday morning.

**Comment by adison93** [comment]
demo OC-8961: https://drive.google.com/file/d/1vg6lM-DBGWNJQ4ZT4xyL-K8Ivmnn6xnz/view?usp=sharing

**Comment by kkrumlian** [comment]
@adison93 I would also like to see a separate PR per story. This will allow us to merge them separately you can do this next time if you don't mind.

**Comment by rooney** [comment]
@kkrumlian PR have been splitted into multiple PRs (one per ticket) and the NOT_APPLICABLE variable is no longer modified, I'm closing this PR.

**Pull request closed without merging**
