### PR TITLE
OC 10861 Move participant ID as part of the JSON body in the create study event endpoint

### PR DESCRIPTION
**Pull request by jkeremian**
Move participant ID as part of the JSON body in the create study event endpoint

### CODE REVIEW

**Comment by svadla-oc** [comment]
retest this please

**Comment by jkeremian** [comment]
what am I retesting?

**Comment by svadla-oc** [comment]
@jkeremian that message is not for you. It was for jenkins to re-run the validation job since the first one marked it as a failed build

**Comment by jkeremian** [comment]
Got you

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
