### PR TITLE
OC-11788 improve performance for Bulk Access Code extract by eliminating multiple calls to get Customer Realm

### PR DESCRIPTION
**Pull request by jkeremian**
improve performance for Bulk Access Code extract by eliminating multiple calls to get Customer Realm

### CODE REVIEW

**Comment by jkeremian** [comment]
Jenkins retest this please

**Comment by svadla-oc** [comment]
can you fix these conflicts please?

**Comment by svadla-oc** [comment]
can you fix the conflicts please?

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
