### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by Taoli2018**

### CODE REVIEW

**Comment by Taoli2018** [comment]
please review the fix and merge the code. Thanks

**Comment by svadla-oc** [comment]
👍

**Comment by svadla-oc** [comment]
we need to create a PR for 3.17.x and assign fix version to the ticket. Also, please add the ticket number to the commit message

**Comment by Taoli2018** [comment]
check the code history, this has been fixed in https://github.com/OpenClinica/OpenClinica/pull/2021

**Pull request closed without merging**
