### PR TITLE
OC-10811 jobUI page sorting and column name relabeling

### PR DESCRIPTION
**Pull request by rooney**
https://jira.openclinica.com/browse/OC-10811?focusedCommentId=181464&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-181464

### CODE REVIEW

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
