### PR TITLE
OC-10472 Provide an ability to capture PII for a bulk list of partici…

### PR DESCRIPTION
**Pull request by yogi-oc**
…pants

OC-10426 Ability to register bulk list of participants for participate with or without capturing their PII

### CODE REVIEW

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by yogi-oc** [comment]
jenkins retest this please

**Comment by jmcinerney** [comment]
jenkins retest this please

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
