### PR TITLE
OC-13323: Removed clear_form button if current form version is archived

### PR DESCRIPTION
**Pull request by suthirr-openclinica**

### CODE REVIEW

**Comment by svadla-oc** [comment]
👍

**Comment by svadla-oc** [comment]
@suthirr-openclinica can you fix the conflicts please?

**Comment by suthirr-openclinica** [comment]
> @suthirr-openclinica can you fix the conflicts please?

Thanks, resolved the conflicts now @svadla-oc

**Comment by svadla-oc** [comment]
👍

**Pull request merged**
